---
- hosts: web_servers
  tasks:
    - name: Update repo
      apt:
        update_cache: yes

    - name: Create HTML
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Hello from Ansible!</h1>"
